name: media_kit
description: A complete video & audio library for Flutter.
homepage: https://github.com/alexmercerind/media_kit
repository: https://github.com/alexmercerind/media_kit
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  meta: ^1.8.0
  path: ^1.8.0
  http: ^0.13.4
  uri_parser:
    git:
      url: https://github.com/harmonoid/uri_parser.git
      ref: b7bf58e856cdd787718883cd7ee2d60e0cf58080
  safe_local_storage:
    git:
      url: https://github.com/harmonoid/safe_local_storage.git
      ref: master

dev_dependencies:
  lints: ^1.0.0

ffigen:
  name: MPV
  output: bin/generated/libmpv/bindings.dart
  headers:
    entry-points:
      - headers/client.h
  dart-bool: true
