name: libmpv
description: A complete video & audio library for Flutter.
homepage: https://github.com/alexmercerind/libmpv.dart
repository: https://github.com/alexmercerind/libmpv.dart
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  path: ^1.8.0
  ffi: ^2.0.1
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0

ffigen:
  name: MPV
  description: A complete video & audio library for Flutter.
  output: bin/generated/bindings.dart
  headers:
    entry-points:
      - headers/client.h
  dart-bool: true
